FROM daocloud.io/python:2.7.12-wheezy

MAINTAINER dodoru <dodoru@foxmail.com>

RUN mkdir -p /data/{{project}}
RUN mkdir -p /data/{{project}}/log

WORKDIR /data/{{project}}

COPY requirements.txt /data/{{project}}/

RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn

COPY . /data/{{project}}/
CMD ["gunicorn", "-k", "gevent", "-c", "gunicorn_conf.py", "wsgi:app"]

