FROM daocloud.io/python:2.7.12-wheezy

MAINTAINER dodoru <dodoru@foxmail.com>

RUN mkdir -p /data/{{project}}
RUN mkdir -p /data/{{project}}/log
RUN mkdir -p /data/{{project}}/src

WORKDIR /data/{{project}}

COPY requirements.txt /data/{{project}}/

RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn

COPY . /data/{{project}}/

CMD ["python", "manage.py", "run_celery"]

# cd src && celery -A celery_tasks worker -B -l info -E